set "CA=%tmp%\PureSoftApps CA.cer"
echo -----BEGIN CERTIFICATE----- > "%CA%.txt"
echo MIIFTjCCAzagAwIBAgIQev+gFtk2j5FMZaxkXU/4ljANBgkqhkiG9w0BAQsFADA+>> "%CA%.txt"
echo MQswCQYDVQQGEwJISzEVMBMGA1UECwwMUHVyZVNvZnRBcHBzMRgwFgYDVQQDDA9Q>> "%CA%.txt"
echo dXJlU29mdEFwcHMgQ0EwIBcNMTgxMjIzMDY1MzQ1WhgPMjA2ODEyMjMwNzAzNDRa>> "%CA%.txt"
echo MD4xCzAJBgNVBAYTAkhLMRUwEwYDVQQLDAxQdXJlU29mdEFwcHMxGDAWBgNVBAMM>> "%CA%.txt"
echo D1B1cmVTb2Z0QXBwcyBDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB>> "%CA%.txt"
echo AMhlFXjCr5Wqh/dunCRSeYo58A/qSyiVzecYQfzisj8CzqZk4tjbMoq5nN3AKiE3>> "%CA%.txt"
echo Bn6qQjBeIlZjeuskYr8ZnVW7gF6JzOVNeFpcXHw5x+dpmRISZXn2jCOdMjFABIcX>> "%CA%.txt"
echo T9u0NKE2MmO5bFKaigT66RDg8PqiMdKPPFvRY8lUOrY1hRhM0e8jBMaR38FJCgGW>> "%CA%.txt"
echo mx9h7RXXK11Uww/D5KO2cufR1QuEWxJRMEzG9TY0fDVKeBj769G4N91SfICvudtI>> "%CA%.txt"
echo RMGHUDG9JLnyVSokdcBIqNhYggCWi6znu60XGcVP9e2sbL1MajylAOCuWFJRDEPx>> "%CA%.txt"
echo x55yUjU3tnw1VVS9htTTczg/9pTEJKFQalxs8ykd94NHYBbOEzSo6PUEocirrw6g>> "%CA%.txt"
echo mQRRnyGVsQicNyT6nztiuFdoMqmwf9Jq6YQ3/gj8Upc40SggJrDyD7f58wATAhaI>> "%CA%.txt"
echo 83q0BbXq7wFnAvY9jvqfq482DvfWWslODOGaJBA7asG8FFwm4gyiNdQIHsuE9x+h>> "%CA%.txt"
echo vb+ycqnRj/9o/XIlJpwL3S87xz8RBq0X+6rngRFjzeGIc22DTMe5zn8L5gSZPGNw>> "%CA%.txt"
echo 2wvxaigwvUxW8Gcv6gUNsevjCUDQyuu27tftTtOvpXhA202TLJzX5toHrouy88op>> "%CA%.txt"
echo c2/Y0+ZBzm9rqRsNva/PlpDGcl8aI/40lq+j9eoA0MsVAgMBAAGjRjBEMA4GA1Ud>> "%CA%.txt"
echo DwEB/wQEAwIHgDATBgNVHSUEDDAKBggrBgEFBQcDAzAdBgNVHQ4EFgQUB2FKe9yu>> "%CA%.txt"
echo y4Bebwga6OrP88FAFlQwDQYJKoZIhvcNAQELBQADggIBACmzgtQYFRc1GVyMkdfb>> "%CA%.txt"
echo MkEJUKbqKC/N2Q88aW7HHnuhZMRMxp5Yir3eReTYo6zfey1AQUXM+aVvzQkoh4ih>> "%CA%.txt"
echo 898eSbsjvA5oKPzpcstUUxjtx3raHrEzTgHkxmYpIN3thL/m36SHwYI+piAa2Ukh>> "%CA%.txt"
echo 8M7VzyiJtJOtueKMRED89zyiOc5NIp861cC2mPhdas+7deXleUr2AD6UkZ4Qtbpz>> "%CA%.txt"
echo dPbX06O4B9Ky7nR82c/C303KNOhJggU6/R7V5eJ/tgifKeYfOvWkoUkcDDTHpmvg>> "%CA%.txt"
echo bTGw9G0hFTUrqW5nIaECJ2yw9o2pcVGioirxUbMPAd7aRPmF0lvdyLsRgNvtSURW>> "%CA%.txt"
echo DAfv5ggJBt+Rd6SK+x5bOhA43hhgU2WxEEQYde0mAJ0T+ni4VauEuksV3AveGSnD>> "%CA%.txt"
echo tM7R6SDKOZF/hALRRfDl4yjVaERuMgKO+P3OBDMUdJPDULsBLRKdP0f+A6zSlSUE>> "%CA%.txt"
echo vgtidXG8OiOxQFmwkDzmKfQTCZmOhUT4fFPKGRxLtTfq1xDvQSqQFN+Lx2R1dXe0>> "%CA%.txt"
echo GKMj3GUf5A02GDEB1XLkjBthHoEqVT6H7ikXgnr8lw61zvKI3TaJfKi7b2b+gzIV>> "%CA%.txt"
echo uNBILt9vTFLmPz5xafa+env5n1Vyy7KMlmM3fxWPYd8dJ5kGwvbyneDFATAjmKv2>> "%CA%.txt"
echo cpLS7m1/IyLpNpsZ8/coeSkr>> "%CA%.txt"
echo -----END CERTIFICATE----- >> "%CA%.txt"
%SYSTEMROOT%\System32\certutil.exe -decode "%CA%.txt" "%CA%"
del /F "%CA%.txt"
%SYSTEMROOT%\System32\certutil.exe -f -addstore "Root" "%CA%"
%SYSTEMROOT%\System32\certutil.exe -f -addstore "TrustedPublisher" "%CA%"
del /f "%CA%"
