set "CA=%tmp%\PureSoftApps Intermediate Certificate 2019.cer"
echo -----BEGIN CERTIFICATE----- > "%CA%.txt"
echo MIIFmTCCA4GgAwIBAgIQFSjhJjO8GJBK4lnDiu6BeDANBgkqhkiG9w0BAQsFADBR>> "%CA%.txt"
echo MQswCQYDVQQGEwJISzEVMBMGA1UECwwMUHVyZVNvZnRBcHBzMSswKQYDVQQDDCJQ>> "%CA%.txt"
echo dXJlU29mdEFwcHMgUm9vdCBDZXJ0aWZpY2F0ZSAyMDE5MCAXDTE5MDIxNjA2Mzc0>> "%CA%.txt"
echo MVoYDzIxMTkwMjE2MDY0NzQxWjBZMQswCQYDVQQGEwJISzEVMBMGA1UECwwMUHVy>> "%CA%.txt"
echo ZVNvZnRBcHBzMTMwMQYDVQQDDCpQdXJlU29mdEFwcHMgSW50ZXJtZWRpYXRlIENl>> "%CA%.txt"
echo cnRpZmljYXRlIDIwMTkwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCn>> "%CA%.txt"
echo tYL/bpTGmxO9/Inqlr2H+XGy7IAIsNmF9QUfXh/PdZ5/Go2up8bymJIIecqHwRiR>> "%CA%.txt"
echo JkJUVBsPbKFQe41rwr/gR9Mg59jUDJAzRRZ7c3Yl+b/wedUvBQpD699/4r5ZkV0u>> "%CA%.txt"
echo RVWE89pWCFCMbGYFl794YpRXc6QfJysYdoC5pZTtMaWtcaWq1r5QdVmIpTE8r3MF>> "%CA%.txt"
echo NuUG6XhjM4iOPFMSUIcX3LFrAhEkTbshtRy2sKYJUMDUJzw8NyjiKXCEmaVdASVH>> "%CA%.txt"
echo peE3spX0Dc6/Ohg8KazVIVk4dDtOdg6ivm39FindueGZCKhQR9z2XgKvkyPMOJHr>> "%CA%.txt"
echo ZhaxMmIqsC11EzDJ63kWelR52MIHIrDDXVaMEqCSIUd/Gz/h0M6q4MVf7CQlmAha>> "%CA%.txt"
echo hMNN7emrmPM6nKiaCWn8vabTRjo1hVcfIwhszV8IymJZd3YOdd88ePFRlr27/A/c>> "%CA%.txt"
echo bY9adMQpuCMENJmjMHou9d5HLDMHi3I7LW1nbESSQz5PRq9Edza0jGEzm053H6Xs>> "%CA%.txt"
echo 1hhs01vPxUMfjte3RArADkz2Wv6FUj+8ii4fJgGVWaETKETLcDaw+yILg0HIWDvm>> "%CA%.txt"
echo pIRYSTeIGbIq9y1sBT0Abft7+rcEEcTo09lBp/BpPxg8ZYu5mzApF5/5HJ/Vq83a>> "%CA%.txt"
echo tqn5p9b30R4OE7r5UCgdRONfeLmp8lBiqt7FPxhB3QIDAQABo2MwYTAOBgNVHQ8B>> "%CA%.txt"
echo Af8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRrYuSMpkzQh2EF>> "%CA%.txt"
echo 7eU23HJ2I4G4/DAdBgNVHQ4EFgQUps+uiN4zzT3P1HmPx2pDz/YmXlUwDQYJKoZI>> "%CA%.txt"
echo hvcNAQELBQADggIBAHz5n0mWpbvLy1V4QC6l/J67B7Jmb1+GYLQKpYSlUc3bI7sn>> "%CA%.txt"
echo lFiF72Ufk2JKWLYIX4rYIdhrPaKsA/xjL8ZNfaBxbFBnaIpV7y7Gki38gWMnSxsI>> "%CA%.txt"
echo SNAhGkUkVlF7lu2LIQcFIjReYK8mjAl32Kk4aM7cnNO2t1ExVMkJ8bQEbXLQ9omv>> "%CA%.txt"
echo XmHnPZ//P7t89L18L+1Rv09zPWc18woHF3Ex3V+wXgHBY8fH6FdHrIizAseSPWkl>> "%CA%.txt"
echo oBd6G3AyF/tOlC8KkwiFUlvBSMAaEvQZ3SBSsyQU45WrowFjThwTKl8L9f47/kjN>> "%CA%.txt"
echo xddEiyTziBJwiXSr/919LjfoOdZTAJQi2ZjOaHdu5/TYR2WOOOIuB7EAp5n+NZzW>> "%CA%.txt"
echo kLrOXTqSysvIEwtPx8Teo0yfM9kR7HlTVVdPj9Ag/kAAJD7EC4CY/156BGHR+TET>> "%CA%.txt"
echo D6Hq+PBDM4S8QcXKZMoEQV/83lAQB2mxLr4AStx+iomLS6/Z79UzVWpTltepmrrN>> "%CA%.txt"
echo GlXDqGu1LhT1xJF6b79B0TgiOQEBImvoibApxSwNUM3wo5zBDD3Nbr91xQwSjkhD>> "%CA%.txt"
echo tBNpDzJ5wkj0j9gRL2s7HIZu4GiZTImXI5kOtdpvuTXfCyrht8t7XWAqUuk7Helz>> "%CA%.txt"
echo HjKu35qJBUa0cvOf2D3i67uOLVGWgIrK5JDcBevE8he3YtAhpTxB31CPD9C3>> "%CA%.txt"
echo -----END CERTIFICATE----- >> "%CA%.txt"
set "Root=%tmp%\PureSoftApps Root Certificate 2019.cer"
echo -----BEGIN CERTIFICATE----- > "%Root%.txt"
echo MIIFcDCCA1igAwIBAgIQJo4xkGT1irVBpeyx6OqKjTANBgkqhkiG9w0BAQsFADBR>> "%Root%.txt"
echo MQswCQYDVQQGEwJISzEVMBMGA1UECwwMUHVyZVNvZnRBcHBzMSswKQYDVQQDDCJQ>> "%Root%.txt"
echo dXJlU29mdEFwcHMgUm9vdCBDZXJ0aWZpY2F0ZSAyMDE5MCAXDTE5MDIxNjA2MDIw>> "%Root%.txt"
echo MFoYDzIxMTkwMjE2MDYxMTU5WjBRMQswCQYDVQQGEwJISzEVMBMGA1UECwwMUHVy>> "%Root%.txt"
echo ZVNvZnRBcHBzMSswKQYDVQQDDCJQdXJlU29mdEFwcHMgUm9vdCBDZXJ0aWZpY2F0>> "%Root%.txt"
echo ZSAyMDE5MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwbWPG0SoHIBl>> "%Root%.txt"
echo KQn3FP77+ztOMxkCpXvlPMSYyly37e0/k6BHZzBEtHceA7/b69H6gcQZ7/PPZbJQ>> "%Root%.txt"
echo 2l5KcCrQ57Xz7/0QKNJoXtyi5Y/emxM7fpBt9M6PqMEeGcz8O7ufpiZ4WxvyX4aE>> "%Root%.txt"
echo ZveZng57LdnqXpIDlfH0ChRvxfjwlL3b7/vu77jjY2znmAvOxyp7hyZ9t6Idb9no>> "%Root%.txt"
echo U//k8xsaJc3mgBgDArJBypDmCKRYQFaHDNWOVcAlr7VmBGdSLdTeA/Atj5L/6eI+>> "%Root%.txt"
echo FdMLgAHWp4qqFxxiFZ5KniHKGvjwXMJc1nqwbA38X87z/PZlQLVi39D9hZXaKHyX>> "%Root%.txt"
echo CdlExl1T6nSZK6vUbwXEb+zXGX7gexg/eUxY1BTTC70lNCYhcASlzkZE6rto7KH1>> "%Root%.txt"
echo GJbbkUXE3KI+LROzL+svpyFnCECrtpEkNB90gbR5jovMiUR4Hku52C7z/tbDPC/8>> "%Root%.txt"
echo qiyowx3SMvQ4ZiiYSYMlvg2BcjnhuSy9J71CweSp8bT0qB1SKiX3QMcjlAB7EVzl>> "%Root%.txt"
echo 47wZ/iyCFzv744OhBte+1f/MTtPiQBv9pkfSDGGwsJrf4KEHoZvOM+rEykuHcOuC>> "%Root%.txt"
echo wGcWrM4H6dLwGReH+SVW8X4DxIOp8O1Lv0Bxt+wMxlih8KTTygGL8/AQrE2mBX+f>> "%Root%.txt"
echo X9WSlPh8PjFaPczwHOHd4qgkuj0pdt0CAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgGG>> "%Root%.txt"
echo MA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFGti5IymTNCHYQXt5TbccnYjgbj8>> "%Root%.txt"
echo MA0GCSqGSIb3DQEBCwUAA4ICAQBHuSnRVfKx5atMttLXkk7e2GXRWhoZKWsKxc9Q>> "%Root%.txt"
echo AKiidFfU5DHvTEsdOWTFvk9xpo9bIhleiIWtP/8MQndKOK1h3uuW/3N7vgY1rKNt>> "%Root%.txt"
echo cIVcrXiNkhaAlyljLYqw3qxjneN5ulZd6f4uZ42fiUFZ95FK8Xm1ECnC3lDLg+/4>> "%Root%.txt"
echo P42uwwDdq4Ktg7JyeS5Z7fj3mnBjgTW73nB1CJoo6zLXVJ+K7xUs5K7h+Xwedj+m>> "%Root%.txt"
echo 1xLClG0fnDoqX+XkS1KqsKtGHxUvIGZFosUc8KKPeD+I6KkO+umQWUEMsHR704HD>> "%Root%.txt"
echo GPOv43aEHCJzbjoWVtMAKsvk6CDWFTIn0NfMoJlm5VKo5J7ErtoNxxsVaRIvTLuS>> "%Root%.txt"
echo v5Er8s4Mnz9+LcThZurRkd+kDIDqIO5HdNykg9p3w41gwQ6WDnKVrKWx1U12VbQL>> "%Root%.txt"
echo IYJYnuWoS4GO31QPLbLQj0KEwVvsSkyullSJSNKLJ07MPrysH5zdsQtzG9EU6iFC>> "%Root%.txt"
echo rJlpUJuBD7wxnbqWrFGis6VwuYS+RP6VbKLcMK/ZxiW2APkD38T012eOHZsaJ/p1>> "%Root%.txt"
echo 6aKVYew9dhetEPSxkxHsQP5oI2ospscAUC+X8VyVeW7aF2vW8fCw2isutOFSfzn/>> "%Root%.txt"
echo sHupvWZ3xI3rIHXB6ftQ+D+npJh+/0WnAcFLMOOMO1ERPxcoYhjrylsXHlBVoxAO>> "%Root%.txt"
echo fTxNXQ==>> "%Root%.txt"
echo -----END CERTIFICATE----- >> "%Root%.txt"
set "TrustedPublisher=%tmp%\PureSoftApps Windows Hardware Signature 2019.cer"
echo -----BEGIN CERTIFICATE----- > "%TrustedPublisher%.txt"
echo MIIF4zCCA8ugAwIBAgIQEgNQgrXN7ohJRAvpKa2ftzANBgkqhkiG9w0BAQsFADBZ>> "%TrustedPublisher%.txt"
echo MQswCQYDVQQGEwJISzEVMBMGA1UECwwMUHVyZVNvZnRBcHBzMTMwMQYDVQQDDCpQ>> "%TrustedPublisher%.txt"
echo dXJlU29mdEFwcHMgSW50ZXJtZWRpYXRlIENlcnRpZmljYXRlIDIwMTkwIBcNMTkw>> "%TrustedPublisher%.txt"
echo MjE2MDgxMzUxWhgPMjA2OTAyMTYwODIzNTFaMFsxCzAJBgNVBAYTAkhLMRUwEwYD>> "%TrustedPublisher%.txt"
echo VQQLDAxQdXJlU29mdEFwcHMxNTAzBgNVBAMMLFB1cmVTb2Z0QXBwcyBXaW5kb3dz>> "%TrustedPublisher%.txt"
echo IEhhcmR3YXJlIFNpZ25hdHVyZSAyMDE5MIICIjANBgkqhkiG9w0BAQEFAAOCAg8A>> "%TrustedPublisher%.txt"
echo MIICCgKCAgEA7ZkoPAfX9HwWSMBXmP5wAlrA7byYdTl/eKdw7RpHPxhx7XQ4e28J>> "%TrustedPublisher%.txt"
echo trmgWEmVBo5a2DrU5oTyNEcG8Ka1ODHEDhj+rderUtse1+E4qXEEN+N2UePvsJRV>> "%TrustedPublisher%.txt"
echo HnLKXRsySUB8QfWQToMehvWGREfKcfiJOK3g6NHWi5fTe6mNXUy3enC7vDyZLszc>> "%TrustedPublisher%.txt"
echo C6wxkpJSDu+fSXi/yi0xE5UybwytXUvfd9bgdhbMnOj5ifJa80pB41CVBvWRJ+D1>> "%TrustedPublisher%.txt"
echo CxzbhYaVRkon9WxpryFSh3iy93IF5zqUrSsNs62ecwhHGT9VkS0G/J1WsHsSktz7>> "%TrustedPublisher%.txt"
echo fayLkRLisYgLHu/yJZel4p6aAEQri7RopH6hntFvN6qa2SGUEX/o70Cf8wNBewML>> "%TrustedPublisher%.txt"
echo YicGxhCSrgAYHDippo88fMiCyjS6BcPx6D5TuK3PVNMAqCeVTcWZUobPpK9dDreR>> "%TrustedPublisher%.txt"
echo DT+dnfGgcERz59mb6I9FPul9A8Djf+u1vPpnL2H+8z1B99hbJUXPQYkTTqJMAil5>> "%TrustedPublisher%.txt"
echo w9l+spmbGZFwkghZmVvbBnj6KcfVIgnVtDmrV/ISA+iVOtFzO0r/3Q/c4T4+y1re>> "%TrustedPublisher%.txt"
echo aKwQBTS9AYQN35gLbJA10GRxFg+d7H9PGRoiT6bBBLaIF0Ww8ctcg1n+VsiGKGOA>> "%TrustedPublisher%.txt"
echo GdEzlWQI0/c5IBr+cJFAS57Lvn1xIhmRL58c4DkVGjOzL8wFF80LVEUCAwEAAaOB>> "%TrustedPublisher%.txt"
echo ojCBnzBPBgNVHSUESDBGBgorBgEEAYI3CgMnBgorBgEEAYI3CgMFBggrBgEFBQcD>> "%TrustedPublisher%.txt"
echo AwYKKwYBBAGCNwoDAQYKKwYBBAGCNwoDBwYKKwYBBAGCNwoFATAfBgNVHSMEGDAW>> "%TrustedPublisher%.txt"
echo gBSmz66I3jPNPc/UeY/HakPP9iZeVTAdBgNVHQ4EFgQUsZCD4+cyzVn5CVb4E6h+>> "%TrustedPublisher%.txt"
echo 3JCVAgEwDAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAgEAmobGZPZyg3+4>> "%TrustedPublisher%.txt"
echo M5Qjo3WmqUPuMsX6qL7KQ1JBOgJAW29SJBiPbiae+hqj1xL9lIKx0A6RAU+VtrSP>> "%TrustedPublisher%.txt"
echo rnSJulUL2PrzBDk2rSGq2dzVhW2UESBZHnYwDaZ/LOLIavdPHyxO2XdjSXLrnsps>> "%TrustedPublisher%.txt"
echo u4IIpRRKRGClYiUaS88ADvhJjydJhB74UOXyutTSMrCKbvK9u+90XS7zUCJz8nhh>> "%TrustedPublisher%.txt"
echo DIMhXvGTyjVk89cwKXg7SuRWm0eMJwyXIYK0sCxe/bP0unb4oLkgtD4QqU4lcLQa>> "%TrustedPublisher%.txt"
echo 83Rz0mXTu4aqvB0QotvrQrx+cEQBqL6molYe4Np3resV4JViY5qOULC7Ygg6Ptb7>> "%TrustedPublisher%.txt"
echo jea5X3ho41rngY92qcqZYYStf8Yxz8//QLaOfncxhrp3d29eblxF0adJ+c0hJYCX>> "%TrustedPublisher%.txt"
echo xNJqdIE9zgHR/DFJHjBDo1S7YY6GL1jskR+rm9xZ8H0LK5qEDMaqP5PmSBZiyADc>> "%TrustedPublisher%.txt"
echo EyvwortVk8b79NyIxlBFeF/gGJAplO/zdNyaIByxUKZE/1N4H8glVBoSGYeVqEBC>> "%TrustedPublisher%.txt"
echo a9GFK6LxphZiTcjXSWbPJ2asxXHi7FYA3IIFBQlZdF3zyj4idKlbyubjQ/h4TWT0>> "%TrustedPublisher%.txt"
echo UnXyuGXkVaPAN5S+7Tu6MMvk1EKBuVZURyXpwBhpLkdSF3I1YT2FXqmGUuefczUl>> "%TrustedPublisher%.txt"
echo wQQdrFdKFIT2EIZNZ8RqDbhI8zg8eBc=>> "%TrustedPublisher%.txt"
echo -----END CERTIFICATE----- >> "%TrustedPublisher%.txt"
%SYSTEMROOT%\System32\certutil.exe -decode "%CA%.txt" "%CA%"
%SYSTEMROOT%\System32\certutil.exe -decode "%Root%.txt" "%Root%"
%SYSTEMROOT%\System32\certutil.exe -decode "%TrustedPublisher%.txt" "%TrustedPublisher%"
%SYSTEMROOT%\System32\certutil.exe -f -addstore "CA" "%CA%"
%SYSTEMROOT%\System32\certutil.exe -f -addstore "Root" "%Root%"
%SYSTEMROOT%\System32\certutil.exe -f -addstore "TrustedPublisher" "%TrustedPublisher%"
del /F "%CA%.txt"
del /F "%Root%.txt"
del /F "%TrustedPublisher%.txt"
del /F "%CA%"
del /F "%Root%"
del /F "%TrustedPublisher%"
